version: '3.7'

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  php: &php
    build:
      context: ./.docker/php
    logging: *default-logging
    volumes:
      - ".:/app"
    working_dir: /app
    environment:
      TERM: "xterm-256color"
    tty: true
    command: sh -c "composer install && php vendor/bin/codecept run -vvv"
